snowflake:
  outputs:
    dev:
      account: IXLTSJR-GA53142
      database: SNOWFLAKE_LEARNING_DB
      password: LeasingVertical@123*
      role: SNOWFLAKE_LEARNING_ROLE
      schema: SOURCE
      threads: 1
      type: snowflake
      user: dbtuser
      warehouse: SNOWFLAKE_LEARNING_WH
  target: dev
