snowflake:
  outputs:
    dev:
      account: IXLTSJR-GA53142
      database: SNOWFLAKE_LEARNING_DB
      password: LeasingVertical@123*
      role: SNOWFLAKE_LEARNING_ROLE
      schema: LV_INTRO_TO_DATA_TRANSFORMATIONS
      threads: 1
      type: snowflake
      user: dbtuser
      warehouse: COMPUTE_WH
  target: dev
